version: "3"

services:
  nodeosd:
    # image: eosio/eos:latest
    image: eosio/eos:v1.2.3
    command: /opt/eosio/bin/nodeosd.sh --http-validate-host=false -e --contracts-console
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - /Users/guoguo/Desktop:/hostdata
      # - /home/guochen/Desktop:/hostdata

  keosd:
    # image: eosio/eos:latest
    image: eosio/eos:v1.2.3
    command: /opt/eosio/bin/keosd --http-validate-host=false
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - /Users/guoguo/Desktop:/hostdata
      # - /home/guochen/Desktop:/hostdata

volumes:
  nodeos-data-volume:
  keosd-data-volume:
